"""
Model Trust Suite
==================
One place to check whether the soft-power modeling pipeline can be trusted:
overfitting, target leakage, temporal/entity generalization, multicollinearity,
Kalman residual structure, forecast-interval calibration, ranking robustness,
and agreement with an external, independently-built benchmark index.

Run from working/ (uses the project's own .venv):

    .venv/Scripts/python.exe model_trust_suite.py

It reads whatever artifacts already exist under output/ (cv_results.json,
feature_importance.csv, kalman_results.csv, sensitivity_analysis.csv, ...)
and additionally trains a couple of small, fresh LightGBM models directly off
output/master_soft_power_panel.csv to run generalization tests the existing
pipeline doesn't already produce (random-split vs temporal-split vs
held-out-country split).

Nothing here is a strict pass/fail unit test suite — these are diagnostic
checks with a verdict (PASS / WARN / FAIL) and a plain-English reason, meant
to be read by a human deciding how much to trust a number on the dashboard.
See MODEL_TRUST_GUIDE.md for the concepts behind each check.
"""

from __future__ import annotations

import json
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# Windows consoles often default to cp1252, which chokes on characters like
# 'Δ' that show up in some of the archived diagnostic labels. Fall back to
# replacing unencodable characters instead of crashing the whole run.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(errors="replace")
    except (AttributeError, ValueError):
        pass

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "output"
REPORT_PATH = ROOT / "trust_report.md"

TARGET_CANDIDATES = ["soft_power_score", "soft_power_score_raw", "soft_power_score_pca"]
COUNTRY_COL = "iso3"
YEAR_COL = "year"

# Columns that are mechanically derived from (or components of) the target.
# These must never be used as model *inputs* when testing genuine predictive
# skill -- they are listed here so every check uses the same definition of
# "leaky" instead of each function guessing its own.
LEAKY_NAME_FRAGMENTS = [
    "soft_power_score", "global_rank", "rank_", "d1_", "d2_", "d3_", "d4_", "d5_",
    "score_roll", "score_lag", "target_score",
]

DIVIDER = "-" * 78


def is_leaky(col: str) -> bool:
    c = col.lower()
    return any(frag in c for frag in LEAKY_NAME_FRAGMENTS)


# ─────────────────────────────────────────────────────────────────────────
# I/O helpers -- every one degrades gracefully if the artifact is missing,
# since this suite should still run on a partial output/ directory.
# ─────────────────────────────────────────────────────────────────────────

def load_json(name: str):
    path = OUT / name
    if not path.exists():
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_csv(name: str) -> pd.DataFrame | None:
    path = OUT / name
    if not path.exists():
        return None
    return pd.read_csv(path)


class Report:
    """Accumulates check results and renders console + markdown output."""

    def __init__(self):
        self.checks = []  # list of dicts: section, name, verdict, detail

    def add(self, section: str, name: str, verdict: str, detail: str):
        self.checks.append({"section": section, "name": name, "verdict": verdict, "detail": detail})
        marker = {"PASS": "[PASS]", "WARN": "[WARN]", "FAIL": "[FAIL]", "INFO": "[INFO]"}[verdict]
        print(f"{marker} {name}")
        for line in detail.strip().splitlines():
            print(f"       {line}")
        print()

    def section(self, title: str):
        print(f"\n{DIVIDER}\n{title}\n{DIVIDER}")

    def write_markdown(self):
        counts = {"PASS": 0, "WARN": 0, "FAIL": 0, "INFO": 0}
        for c in self.checks:
            counts[c["verdict"]] += 1

        lines = [
            "# Model Trust Report",
            "",
            "Auto-generated by `model_trust_suite.py`. Do not hand-edit -- rerun the",
            "script after retraining or refreshing `output/` to regenerate.",
            "",
            f"**Summary:** {counts['PASS']} pass, {counts['WARN']} warn, "
            f"{counts['FAIL']} fail, {counts['INFO']} info.",
            "",
            "| Section | Check | Verdict |",
            "|---|---|---|",
        ]
        for c in self.checks:
            lines.append(f"| {c['section']} | {c['name']} | {c['verdict']} |")

        lines.append("")
        current_section = None
        for c in self.checks:
            if c["section"] != current_section:
                current_section = c["section"]
                lines.append(f"\n## {current_section}\n")
            lines.append(f"### {c['name']} — **{c['verdict']}**\n")
            lines.append(c["detail"].strip() + "\n")

        REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
        print(f"\nFull report written to {REPORT_PATH.relative_to(ROOT.parent)}")


# ─────────────────────────────────────────────────────────────────────────
# 1. Read back the CV metrics the training pipeline already produced and
#    sanity-check them (very high R^2 and CI-coverage drift are the two
#    classic "looks great, isn't" signals).
# ─────────────────────────────────────────────────────────────────────────

def check_cv_metrics(report: Report):
    report.section("1. Cross-validated model metrics (from output/)")

    multi = load_json("multi_model_cv_results.json")
    single = load_json("cv_results.json")

    if multi is None and single is None:
        report.add("CV metrics", "multi_model_cv_results.json / cv_results.json",
                    "INFO", "Neither file found -- run the phase 2/phase C training scripts first.")
        return

    rows = []
    if multi:
        for model_name, m in multi.items():
            if not isinstance(m, dict) or "r2_mean" not in m:
                continue
            rows.append((model_name, m.get("r2_mean"), m.get("mae_mean"), m.get("ci_coverage")))
    elif single:
        rows.append(("(single model)", single.get("r2_mean"), single.get("mae_mean"), single.get("ci_coverage")))

    detail_lines = [f"{'model':<14}{'r2_mean':>10}{'mae_mean':>10}{'ci_coverage':>13}"]
    worst_r2_flag = False
    worst_cov_flag = False
    for name, r2, mae, cov in rows:
        detail_lines.append(f"{name:<14}{r2 if r2 is not None else float('nan'):>10.4f}"
                             f"{mae if mae is not None else float('nan'):>10.4f}"
                             f"{cov if cov is not None else float('nan'):>13.4f}")
        if r2 is not None and r2 > 0.95:
            worst_r2_flag = True
        if cov is not None and abs(cov - 0.80) > 0.15:
            worst_cov_flag = True

    verdict = "PASS"
    tail = []
    if worst_r2_flag:
        verdict = "WARN"
        tail.append(
            "R^2 above ~0.95 on a 0-100 bounded composite score is unusually high. "
            "It is very likely inflated by score-momentum features (rolling mean / lag of "
            "the target itself) rather than the underlying KPI indicators -- see the "
            "'target leakage in feature importance' and 'naive-baseline gap' checks below "
            "before treating this as genuine model skill."
        )
    if worst_cov_flag:
        verdict = "WARN" if verdict == "PASS" else verdict
        tail.append(
            "ci_coverage (the fraction of held-out points that actually fell inside the "
            "predicted interval) drifts more than 15 points from the intended ~80% nominal "
            "coverage for at least one model. That means the reported confidence interval "
            "is miscalibrated -- either overconfident (coverage too low, intervals too "
            "narrow) or underconfident (coverage too high, intervals too wide)."
        )
    if not tail:
        tail.append("R^2 and interval coverage both look in a defensible range.")

    report.add("CV metrics", "Per-model CV R^2 / MAE / CI coverage", verdict,
               "\n".join(detail_lines) + "\n\n" + "\n".join(tail))


# ─────────────────────────────────────────────────────────────────────────
# 2. Target leakage scan over the persisted feature-importance table.
# ─────────────────────────────────────────────────────────────────────────

def check_feature_importance_leakage(report: Report):
    report.section("2. Target-leakage scan over feature_importance.csv")

    fi = load_csv("feature_importance.csv")
    if fi is None or "feature" not in fi.columns:
        report.add("Leakage scan", "feature_importance.csv", "INFO", "File not found or missing 'feature' column.")
        return

    imp_col = "importance" if "importance" in fi.columns else fi.columns[-1]
    fi = fi.sort_values(imp_col, ascending=False).reset_index(drop=True)
    total = fi[imp_col].sum()
    fi["leaky"] = fi["feature"].apply(is_leaky)
    leaky_share = fi.loc[fi["leaky"], imp_col].sum() / total if total else 0.0

    top = fi.head(10)
    lines = [f"{'feature':<32}{'importance':>12}{'leaky?':>8}"]
    for _, row in top.iterrows():
        lines.append(f"{row['feature']:<32}{row[imp_col]:>12.3f}{'yes' if row['leaky'] else '':>8}")
    lines.append(f"\nShare of total importance on target-derived features (lag/rolling score, "
                 f"dimension sub-scores, rank): {leaky_share:.1%}")

    if leaky_share > 0.40:
        verdict = "WARN"
        lines.append(
            "\nMore than 40% of the model's importance sits on features that are mechanically "
            "derived from the target's own history (e.g. score_roll3_mean, score_lag1). This "
            "is not a bug -- the training script deliberately lags them by 1+ year so it isn't "
            "same-row leakage -- but it means most of the model's accuracy is 'soft power this "
            "year is close to soft power last year', not 'these KPIs explain soft power'. Report "
            "R^2 alongside the naive-baseline comparison (check 3), not on its own."
        )
    else:
        verdict = "PASS"
        lines.append("\nImportance is not dominated by target-derived features.")

    report.add("Leakage scan", "Share of importance on target-derived features", verdict, "\n".join(lines))


# ─────────────────────────────────────────────────────────────────────────
# 3. Does the full KPI model actually beat a naive / lag-only baseline?
#    (Reuses output already produced by archive/diagnostic_aftermodelout.py.)
# ─────────────────────────────────────────────────────────────────────────

def check_naive_baseline_gap(report: Report):
    report.section("3. Naive-baseline comparison (level model and delta model)")

    level = load_json("diagnostic_1_autocorrelation.json")
    delta = load_json("diagnostic_2_delta.json")

    if level:
        by_label = {row["label"]: row for row in level}
        lines = [f"{'variant':<28}{'mae_mean':>10}{'r2_mean':>10}"]
        for row in level:
            lines.append(f"{row['label']:<28}{row['mae_mean']:>10.4f}{row['r2_mean']:>10.4f}")

        naive = by_label.get("naive (next = current)")
        lag_only = by_label.get("lag-only XGBoost")
        full = by_label.get("full XGBoost (KPIs)")

        verdict = "PASS"
        tail = []
        if full and lag_only and full["r2_mean"] <= lag_only["r2_mean"]:
            verdict = "WARN"
            tail.append(
                "The full KPI model does not beat the lag-only model (which only sees the "
                "country's own score history). The independent KPI indicators are adding "
                "little to no predictive power beyond 'soft power persists year over year' -- "
                "treat the model as a momentum/smoothing model first, a causal explainer second."
            )
        if naive and full and full["r2_mean"] <= naive["r2_mean"]:
            verdict = "FAIL"
            tail.append(
                "The full model does not even beat the trivial 'next year = this year' "
                "baseline. Any R^2 quoted for this model in isolation is misleading."
            )
        if not tail:
            tail.append("Full KPI model clears both the naive and lag-only baselines.")

        report.add("Naive baseline", "Level prediction vs naive / lag-only baselines", verdict,
                   "\n".join(lines) + "\n\n" + "\n".join(tail))
    else:
        report.add("Naive baseline", "diagnostic_1_autocorrelation.json", "INFO", "File not found.")

    if delta:
        cv = delta.get("cv_results", [])
        lines = [f"{'variant':<28}{'mae_mean':>10}{'r2_mean':>10}"]
        worst = True
        for row in cv:
            lines.append(f"{row['label']:<28}{row['mae_mean']:>10.4f}{row['r2_mean']:>10.4f}")
            if row["r2_mean"] > 0:
                worst = False
        verdict = "FAIL" if worst else "WARN"
        tail = (
            "All delta (year-over-year change) variants have R^2 <= 0 in cross-validation, "
            "meaning none of them explain more variance than predicting zero change every "
            "year. Do not present 'predicted delta' / rise-fall forecasts as reliable -- they "
            "are directionally suggestive at best. This is exactly why the dashboard's forecast "
            "panel instead carries the Kalman state forward rather than trusting the delta model."
            if worst else
            "At least one delta variant beats the zero-change baseline, but margins are thin -- "
            "treat delta/rise-fall predictions as low-confidence."
        )
        report.add("Naive baseline", "Delta (change) prediction vs zero-change baseline", verdict,
                   "\n".join(lines) + "\n\n" + tail)
    else:
        report.add("Naive baseline", "diagnostic_2_delta.json", "INFO", "File not found.")


# ─────────────────────────────────────────────────────────────────────────
# 4. Fresh generalization test: random split vs temporal split vs held-out
#    countries, trained directly off output/master_soft_power_panel.csv.
#    This is the check the existing pipeline does NOT already produce.
# ─────────────────────────────────────────────────────────────────────────

def _feature_columns(df: pd.DataFrame, target: str) -> list[str]:
    non_numeric = {COUNTRY_COL, YEAR_COL, "canonical"}
    cols = []
    for c in df.columns:
        if c in non_numeric or c == target:
            continue
        if is_leaky(c):
            continue
        if pd.api.types.is_numeric_dtype(df[c]):
            cols.append(c)
    return cols


def _fit_eval(train_df, test_df, feature_cols, target):
    import lightgbm as lgb
    from sklearn.metrics import mean_absolute_error, r2_score

    model = lgb.LGBMRegressor(
        n_estimators=300, max_depth=6, learning_rate=0.05,
        subsample=0.8, colsample_bytree=0.8, random_state=42, verbosity=-1,
    )
    model.fit(train_df[feature_cols], train_df[target])
    pred = model.predict(test_df[feature_cols])
    return r2_score(test_df[target], pred), mean_absolute_error(test_df[target], pred)


def check_generalization_splits(report: Report):
    report.section("4. Random split vs temporal split vs held-out-country split (fresh models)")

    panel_path = OUT / "master_soft_power_panel.csv"
    if not panel_path.exists():
        report.add("Generalization", "master_soft_power_panel.csv", "INFO", "Panel file not found -- skipped.")
        return

    try:
        import lightgbm  # noqa: F401
    except ImportError:
        report.add("Generalization", "lightgbm", "INFO", "lightgbm not installed -- skipped.")
        return

    df = pd.read_csv(panel_path)
    target = next((t for t in TARGET_CANDIDATES if t in df.columns), None)
    if target is None:
        report.add("Generalization", "target column", "INFO", "No known target column found -- skipped.")
        return

    df = df.dropna(subset=[target]).copy()
    feature_cols = _feature_columns(df, target)
    df[feature_cols] = df[feature_cols].apply(pd.to_numeric, errors="coerce")

    from sklearn.model_selection import train_test_split, GroupShuffleSplit

    # (a) random row split -- ignores that rows are a country/year panel
    train_r, test_r = train_test_split(df, test_size=0.2, random_state=42)
    r2_random, mae_random = _fit_eval(train_r, test_r, feature_cols, target)

    # (b) temporal split -- train on the past, test on years the model has
    #     never seen for ANY country (the honest test for a forecasting tool)
    cutoff = int(df[YEAR_COL].quantile(0.80))
    train_t = df[df[YEAR_COL] <= cutoff]
    test_t = df[df[YEAR_COL] > cutoff]
    if len(test_t) >= 20:
        r2_temporal, mae_temporal = _fit_eval(train_t, test_t, feature_cols, target)
    else:
        r2_temporal = mae_temporal = None

    # (c) held-out countries -- train on 80% of countries, test on entirely
    #     unseen countries (the honest test for "does this generalize to a
    #     country the model was never trained on")
    gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
    train_idx, test_idx = next(gss.split(df, groups=df[COUNTRY_COL]))
    train_g, test_g = df.iloc[train_idx], df.iloc[test_idx]
    r2_group, mae_group = _fit_eval(train_g, test_g, feature_cols, target)

    lines = [
        f"Target: {target}   |   {len(feature_cols)} non-leaky numeric features   |   {len(df)} rows",
        "",
        f"{'split':<28}{'r2':>10}{'mae':>10}",
        f"{'random 80/20 rows':<28}{r2_random:>10.4f}{mae_random:>10.4f}",
    ]
    if r2_temporal is not None:
        lines.append(f"{'temporal (train<=' + str(cutoff) + ')':<28}{r2_temporal:>10.4f}{mae_temporal:>10.4f}")
    lines.append(f"{'held-out countries (20%)':<28}{r2_group:>10.4f}{mae_group:>10.4f}")

    gaps = [r2_random - r2_group]
    gap_desc = [f"random-vs-held-out-country R^2 gap = {gaps[0]:.4f}"]
    if r2_temporal is not None:
        gaps.append(r2_random - r2_temporal)
        gap_desc.append(f"random-vs-temporal R^2 gap = {gaps[-1]:.4f}")

    max_gap = max(gaps)
    if max_gap > 0.15:
        verdict = "WARN"
        tail = (
            "A random row split scores notably better than a temporal or held-out-country "
            "split. That gap is the honest measure of overfitting for panel data: a random "
            "split lets the model see other rows from the *same* country (and nearby years) "
            "during training, which is much easier than truly predicting an unseen country or "
            "future year. Trust the temporal/held-out-country numbers, not the random-split "
            "number, when judging real-world accuracy."
        )
    elif max_gap > 0.05:
        verdict = "WARN"
        tail = "Moderate gap between random and structured splits -- some optimism in the random-split number, worth keeping in mind but not alarming."
    else:
        verdict = "PASS"
        tail = "Random, temporal, and held-out-country splits score similarly -- no strong sign of the model exploiting row-level shortcuts."

    lines.append("\n" + "\n".join(gap_desc))
    report.add("Generalization", "Random vs temporal vs held-out-country R^2", verdict, "\n".join(lines) + "\n\n" + tail)


# ─────────────────────────────────────────────────────────────────────────
# 5. Multicollinearity among the input KPI features (VIF, computed by hand
#    with sklearn LinearRegression so no extra dependency is required).
# ─────────────────────────────────────────────────────────────────────────

def check_multicollinearity(report: Report):
    report.section("5. Multicollinearity among input KPI features (VIF)")

    panel_path = OUT / "master_soft_power_panel.csv"
    if not panel_path.exists():
        report.add("Multicollinearity", "master_soft_power_panel.csv", "INFO", "Panel file not found -- skipped.")
        return

    df = pd.read_csv(panel_path)
    target = next((t for t in TARGET_CANDIDATES if t in df.columns), None)
    feature_cols = _feature_columns(df, target or "")

    # Keep raw (non-normalized) indicator columns only -- VIF on the already
    # normalized/duplicated norm_* columns would just restate the same signal.
    feature_cols = [c for c in feature_cols if not c.startswith("norm_") and not c.startswith("outlier")]

    sub = df[feature_cols].apply(pd.to_numeric, errors="coerce")
    # Need enough complete rows per column pair; keep columns with <40% missing,
    # then drop rows with any remaining gap, then median-fill any stragglers.
    keep = [c for c in sub.columns if sub[c].isna().mean() < 0.4]
    sub = sub[keep].fillna(sub[keep].median())

    from sklearn.linear_model import LinearRegression

    vifs = {}
    cols = list(sub.columns)
    for i, col in enumerate(cols):
        y = sub[col].values
        X = sub.drop(columns=[col]).values
        if X.shape[1] == 0 or np.std(y) == 0:
            continue
        r2 = LinearRegression().fit(X, y).score(X, y)
        vifs[col] = 1.0 / (1.0 - r2) if r2 < 0.999 else float("inf")

    vif_series = pd.Series(vifs).sort_values(ascending=False)
    high = vif_series[vif_series > 10]

    lines = ["Top 10 VIF values (>10 conventionally flags problematic redundancy):", ""]
    for name, v in vif_series.head(10).items():
        lines.append(f"  {name:<32}{v:>8.2f}")
    lines.append(f"\n{len(high)} of {len(vif_series)} features have VIF > 10.")

    if len(high) > 0:
        verdict = "WARN"
        lines.append(
            "\nHighly collinear inputs don't hurt tree-model (XGBoost/LightGBM/RF) point "
            "predictions much, but they do destabilize per-feature attribution: SHAP/importance "
            "can arbitrarily split credit between two features that carry almost the same "
            "information. Read single-feature SHAP explanations for these features as "
            "'this cluster of related indicators mattered', not as a precise ranking within "
            "the cluster. Ridge/linear coefficients on these features (ridge_coefficients.csv) "
            "are the ones most at risk of being unstable."
        )
    else:
        verdict = "PASS"
        lines.append("\nNo strongly redundant feature pairs found.")

    report.add("Multicollinearity", "VIF over raw KPI inputs", verdict, "\n".join(lines))


# ─────────────────────────────────────────────────────────────────────────
# 6. Kalman filter residual (innovation) autocorrelation -- if the filter is
#    well-specified, innovations should look like white noise.
# ─────────────────────────────────────────────────────────────────────────

def check_kalman_residuals(report: Report):
    report.section("6. Kalman filter residual (innovation) autocorrelation")

    kal = load_csv("kalman_results.csv")
    if kal is None or "innovation" not in kal.columns:
        report.add("Kalman diagnostics", "kalman_results.csv", "INFO", "File not found or missing 'innovation' column.")
        return

    autocorrs = []
    for iso3, grp in kal.groupby(COUNTRY_COL):
        s = grp.sort_values(YEAR_COL)["innovation"].dropna()
        if len(s) < 5:
            continue
        a, b = s.values[:-1], s.values[1:]
        if np.std(a) == 0 or np.std(b) == 0:
            continue
        autocorrs.append(np.corrcoef(a, b)[0, 1])

    if not autocorrs:
        report.add("Kalman diagnostics", "lag-1 innovation autocorrelation", "INFO", "Not enough per-country data to compute.")
        return

    mean_ac = float(np.mean(autocorrs))
    frac_strong = float(np.mean(np.abs(np.array(autocorrs)) > 0.3))

    lines = [
        f"Countries checked: {len(autocorrs)}",
        f"Mean lag-1 autocorrelation of innovations: {mean_ac:+.3f}",
        f"Share of countries with |autocorrelation| > 0.3: {frac_strong:.1%}",
    ]

    if abs(mean_ac) > 0.2 or frac_strong > 0.3:
        verdict = "WARN"
        lines.append(
            "\nInnovations (the filter's one-step residuals) are not close to white noise for "
            "a meaningful share of countries. That suggests the fixed Q/R noise parameters "
            "(process noise = 30% of score-diff variance, observation noise = 10% of score "
            "variance, hard-coded in kalman_softpower.py) are a systematic mis-fit for some "
            "countries -- the filter is either lagging behind real trend changes or "
            "over-reacting to single-year blips for them. The published CI width is only "
            "trustworthy where residuals actually look like noise."
        )
    else:
        verdict = "PASS"
        lines.append("\nInnovations look close to white noise on average -- the fixed Q/R choice is a reasonable fit.")

    report.add("Kalman diagnostics", "Innovation white-noise check", verdict, "\n".join(lines))


# ─────────────────────────────────────────────────────────────────────────
# 7. Kalman confidence-interval calibration: does the stated 95% band
#    actually contain ~95% of the observed scores?
# ─────────────────────────────────────────────────────────────────────────

def check_kalman_ci_calibration(report: Report):
    report.section("7. Kalman 95% CI calibration")

    kal = load_csv("kalman_results.csv")
    needed = {"raw_score", "ci_lower_95", "ci_upper_95"}
    if kal is None or not needed.issubset(kal.columns):
        report.add("CI calibration", "kalman_results.csv", "INFO", "File not found or missing required columns.")
        return

    sub = kal.dropna(subset=list(needed))
    inside = (sub["raw_score"] >= sub["ci_lower_95"]) & (sub["raw_score"] <= sub["ci_upper_95"])
    coverage = float(inside.mean())

    lines = [
        f"Observations checked: {len(sub)}",
        f"Empirical coverage of the stated 95% band: {coverage:.1%}  (nominal target: 95%)",
        "",
        "Caveat: this compares each year's smoothed estimate's CI against the SAME year's "
        "observation the filter already used to update itself, not a true out-of-sample "
        "forecast -- so it is a lower bound on how good calibration could look, not a "
        "substitute for backtesting kalman_forecast_5yr.csv against years that have since "
        "become observable.",
    ]

    if abs(coverage - 0.95) > 0.15:
        verdict = "WARN"
        lines.append(
            "\nCoverage is far from the nominal 95%, which usually means the band is too "
            "wide (over-covers) because Q/R were both set as fixed fractions of variance "
            "rather than fit per country. Treat the shaded band on the forecast panel as "
            "indicative of relative uncertainty across countries, not a literal 95% guarantee."
        )
    else:
        verdict = "PASS"
        lines.append("\nCoverage is close to nominal.")

    report.add("CI calibration", "Empirical vs nominal 95% coverage", verdict, "\n".join(lines))


# ─────────────────────────────────────────────────────────────────────────
# 8. Ranking robustness: do XGBoost / PCA / equal-weight / literature
#    weighting schemes agree on country rank? (Reuses sensitivity_analysis.csv.)
# ─────────────────────────────────────────────────────────────────────────

def check_ranking_robustness(report: Report):
    report.section("8. Country-ranking robustness across weighting schemes")

    sens = load_csv("sensitivity_analysis.csv")
    rank_cols = [c for c in (sens.columns if sens is not None else []) if c.startswith("rank_")]
    if sens is None or len(rank_cols) < 2:
        report.add("Ranking robustness", "sensitivity_analysis.csv", "INFO", "File not found or fewer than 2 rank_* columns.")
        return

    corr = sens[rank_cols].corr(method="spearman")
    base = rank_cols[0]
    lines = [f"Spearman rank correlation against '{base}':"]
    worst = 1.0
    for c in rank_cols[1:]:
        v = corr.loc[base, c]
        worst = min(worst, v)
        lines.append(f"  {c:<16}{v:.3f}")

    if worst < 0.7:
        verdict = "WARN"
        lines.append(
            "\nAt least one alternative weighting scheme disagrees substantially with the "
            "primary ranking. Present exact rank positions (especially mid-table, where gaps "
            "between countries are small) as approximate, and prefer talking about a country's "
            "score band or tier over a single ordinal rank in the write-up / dashboard copy."
        )
    else:
        verdict = "PASS"
        lines.append("\nRankings agree well (Spearman > 0.7) across the alternative weighting schemes tested.")

    report.add("Ranking robustness", "Spearman agreement across scoring methods", verdict, "\n".join(lines))


# ─────────────────────────────────────────────────────────────────────────
# 9. External validity: does the model's own ranking agree with published,
#    independent soft-power / nation-reputation indices it was never fit to?
#    Every check above only proves the model is statistically well-behaved
#    (doesn't overfit, isn't leaky, is stable across re-weighting) -- none of
#    them touch whether the *score itself* means anything outside this
#    pipeline. This one does, against four differently-constructed sources.
# ─────────────────────────────────────────────────────────────────────────

# Each entry: (reference csv, rank column in that csv, human label, min rows
# to bother computing a correlation, one-line description of what the index
# actually measures and how it was built -- printed so a reader can judge
# *why* agreement or disagreement is meaningful, not just the number).
EXTERNAL_BENCHMARKS = [
    {
        "file": "external_benchmark_gspi2024.csv",
        "rank_col": "gspi_rank_2024",
        "label": "Brand Finance Global Soft Power Index 2024",
        "min_n": 8,
        "note": "Published survey-based index, 193 UN member states, 170,000+ respondents "
                "across 100+ countries. 20-country reference subset hand-transcribed from "
                "public reporting (the full index sits behind Brand Finance's PDF report) -- "
                "deliberately spans rank 1-193 rather than clustering at the top.",
    },
    {
        "file": "external_benchmark_nbi2023.csv",
        "rank_col": "nbi_rank_2023",
        "label": "Anholt-Ipsos Nation Brands Index 2023",
        "min_n": 8,
        "note": "Published perception survey (Exports, Governance, Culture, People, Tourism, "
                "Immigration, Investment), ~60,000 interviews across 20 panel countries rating "
                "60 nations. Full 60-nation table transcribed from Ipsos's own press-release "
                "PDF (3 non-sovereign entries -- Scotland, Wales, Northern Ireland -- dropped, "
                "no iso3 to join on).",
    },
    {
        "file": "external_benchmark_gci2023.csv",
        "rank_col": "gci_rank_2023",
        "label": "Good Country Index 2023 (v1.6)",
        "min_n": 8,
        "note": "Simon Anholt's index of what a country contributes to the *common good* "
                "(science, culture, peace & security, world order, planet & climate, "
                "prosperity & equality, health & wellbeing) rather than to its own reputation "
                "or influence -- a genuinely different construct from 'soft power', included "
                "deliberately as a check on whether this model conflates the two. Top-50 table "
                "transcribed from Wikipedia's summary of the published index.",
    },
    {
        "file": "external_benchmark_sp30_2019.csv",
        "rank_col": "sp30_rank_2019",
        "label": "Portland/USC Soft Power 30 (2019, final edition)",
        "min_n": 8,
        "note": "The index this pipeline's own name and six-pillar framing most directly "
                "echoes (enterprise, culture, digital, government, engagement, education) -- "
                "discontinued after 2019, so this is a dated comparison. Only 11 of 30 ranked "
                "countries could be reliably sourced from press coverage (the full table lives "
                "in an image-only PDF this suite can't OCR); treat this one as the weakest-"
                "evidence benchmark of the four.",
    },
]


def _run_one_benchmark(report: Report, cfg: dict, preds: pd.DataFrame, source: str):
    path = ROOT / cfg["file"]
    if not path.exists():
        report.add("External benchmark", cfg["file"], "INFO", "Reference file not found -- skipped.")
        return

    bench = pd.read_csv(path)
    merged = bench.merge(preds[[COUNTRY_COL, "global_rank"]], left_on="iso3", right_on=COUNTRY_COL, how="inner")
    if len(merged) < cfg["min_n"]:
        report.add("External benchmark", cfg["label"], "INFO",
                   f"Only {len(merged)} countries overlap between the model output and this "
                   "reference file -- too few to say anything about correlation.")
        return

    rank_col = cfg["rank_col"]
    corr = merged[["global_rank", rank_col]].corr(method="spearman").iloc[0, 1]

    lines = [
        f"Model ranking source: {source}",
        f"Reference: {cfg['label']}",
        cfg["note"],
        "",
        f"{'iso3':<6}{'country':<24}{'model_rank':>12}{'benchmark_rank':>16}",
    ]
    for _, row in merged.sort_values(rank_col).iterrows():
        lines.append(f"{row['iso3']:<6}{row['country']:<24}{int(row['global_rank']):>12}{int(row[rank_col]):>16}")
    lines.append(f"\nSpearman rank correlation (model vs. {cfg['label']}), n={len(merged)}: {corr:.3f}")

    if corr >= 0.5:
        verdict = "PASS"
        lines.append(
            "\nStrong positive agreement with an independent, differently-constructed index -- "
            "good evidence this dimension of the ranking reflects something real, not just an "
            "artifact of this pipeline's own feature engineering."
        )
    elif corr >= 0.2:
        verdict = "WARN"
        lines.append(
            "\nWeak-to-moderate agreement. Some countries likely rank very differently between "
            "this pipeline and the reference index -- worth spot-checking the biggest "
            "disagreements individually rather than citing either ranking as ground truth."
        )
    else:
        verdict = "FAIL" if corr < 0 else "WARN"
        lines.append(
            "\nLittle to no agreement with this benchmark. If the benchmark measures a "
            "genuinely different construct (see the note above), that alone can explain a low "
            "correlation and isn't necessarily a problem -- but if it claims to measure the same "
            "thing this model does, low agreement is worth investigating before citing either "
            "ranking as authoritative."
        )

    report.add("External benchmark", f"Model rank vs. {cfg['label']}", verdict, "\n".join(lines))


def check_external_benchmark(report: Report):
    report.section("9. External benchmark agreement (four independent country-ranking indices)")

    preds = load_csv("soft_power_predictions.csv")
    source = "soft_power_predictions.csv"
    if preds is None or "global_rank" not in preds.columns:
        panel = load_csv("master_soft_power_panel.csv")
        if panel is not None and "global_rank" in panel.columns:
            latest_year = panel.dropna(subset=["global_rank"])[YEAR_COL].max()
            preds = panel[panel[YEAR_COL] == latest_year]
            source = f"master_soft_power_panel.csv (year={latest_year})"
        else:
            preds = None

    if preds is None:
        report.add("External benchmark", "soft_power_predictions.csv / master_soft_power_panel.csv", "INFO",
                   "No file with a global_rank column found -- skipped.")
        return

    for cfg in EXTERNAL_BENCHMARKS:
        _run_one_benchmark(report, cfg, preds, source)


# ─────────────────────────────────────────────────────────────────────────

def main():
    report = Report()
    print("Model Trust Suite -- soft power pipeline")
    print(f"Reading artifacts from: {OUT}")

    check_cv_metrics(report)
    check_feature_importance_leakage(report)
    check_naive_baseline_gap(report)
    check_generalization_splits(report)
    check_multicollinearity(report)
    check_kalman_residuals(report)
    check_kalman_ci_calibration(report)
    check_ranking_robustness(report)
    check_external_benchmark(report)

    report.write_markdown()


if __name__ == "__main__":
    main()
